language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pawate95/react-test -f ./client Dockerfile.dev .

script:
  - docker run -e CI=true pawate95/docker-react npm run test

after_success:
  - docker build -t pawate95/multi-client ./client
  - docker build -t pawate95/multi-nginx ./nginx
  - docker build -t pawate95/multi-server ./server
  - docker build -t pawate95/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pawate95/multi-client
  - docker push pawate95/multi-nginx
  - docker push pawate95/multi-server
  - docker push pawate95/multi-worker

